server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymemntdb
    username: hbstudent1
    password: hbstudent1
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296
#  eureka:
#    instances:
#      prefer-ip-address: true
#    client:
#      fetch-registry: true
#      register-with-eureka: true
#      service-url:
#        defaultZon: http://localhost:8761/eureka
